title = "All Kings Fall"
baseURL = "/"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "except for you of course!"
    author = "Unibear Studio"
    description = "In every generation kings come to power. Some gain their crowns through bloody conquest. Others the lucky sons of old rulers. Yet one thing is clear: All kings fall. Except for you of course! "
    logoBig = "/images/AllKingsFall-LogoONWHITE.png"
    logoSmall = "/images/AllKingsFall-LogoONWHITE.png"
    favicon = "/images/favicon.ico"
    opengraphImage = "/images/AllKingsFall-LogoONWHITE.png"
    twitter = "unibearstudio"
    linkedin = ""
    github = ""
    facebook = ""
    email = ""
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Contents"
    url  = "/#contents"
    weight = 2
[[menu.main]]
    name = "Rulebook"
    url  = "/#rulebook"
    weight = 3